version: '3.1'

services:
  db:
    image: postgis/postgis:13-3.0-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./.tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mlalert
      POSTGRES_DB: mlalert
      POSTGRES_PASSWORD: mlalert
